#!/usr/bin/env zsh

REPLACER='
local boilerplate = [=[
  (:refer-clojure :exclude [def defn defmethod defrecord fn letfn])
  (:require [clojure.pprint :refer [pprint]])
  (:require [schema.core :as s :refer [def defn defmethod defrecord defschema fn letfn]])
  (:require [taoensso.timbre :as timbre
             :refer [trace debug info warn error fatal
                     tracef debugf infof warnf errorf fatalf]])
]=]
local fd = io.open(file, "r+b")
local data = fd:read("*a")
fd:seek("set", 0)
fd:write((data:gsub("  %(:refer%-clojure.-(  %(:require\n)", boilerplate.."%1")))
fd:close()
'

find src -name '*.clj' | while read file; do
  echo $file
  lua -e "file='$file'" -e $REPLACER
done
